-- V10: tabla de usuarios del sistema (RF01 - CU01 Iniciar sesion)
CREATE TABLE usuario (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(100) NOT NULL,
    correo          VARCHAR(120) NOT NULL,
    contrasena_hash VARCHAR(100) NOT NULL,
    rol             VARCHAR(20)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT now(),

    CONSTRAINT pk_usuario        PRIMARY KEY (id),
    CONSTRAINT uk_usuario_correo UNIQUE (correo),
    CONSTRAINT ck_usuario_rol    CHECK (rol IN ('COMERCIAL', 'GERENCIA', 'ADMIN'))
);