-- V12: tabla de clientes (RF02 - CU03 Registrar cliente, CU04 Validar datos del cliente)
CREATE TABLE cliente (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento    VARCHAR(3)   NOT NULL,
    numero_documento  VARCHAR(11)  NOT NULL,
    razon_social      VARCHAR(150) NOT NULL,
    tipo_cliente      VARCHAR(20)  NOT NULL,
    persona_contacto  VARCHAR(100),
    telefono          VARCHAR(9)   NOT NULL,
    correo            VARCHAR(120),
    direccion         VARCHAR(200),
    registrado_por_id BIGINT       NOT NULL,
    fecha_registro    TIMESTAMP    NOT NULL DEFAULT now(),
    editado_por_id    BIGINT,
    fecha_edicion     TIMESTAMP,

    CONSTRAINT pk_cliente                  PRIMARY KEY (id),
    CONSTRAINT uk_cliente_numero_documento UNIQUE (numero_documento),
    CONSTRAINT ck_cliente_tipo_documento   CHECK (tipo_documento IN ('RUC', 'DNI')),
    CONSTRAINT ck_cliente_tipo_cliente     CHECK (tipo_cliente IN ('CONFECCIONISTA', 'DISTRIBUIDOR', 'INSTITUCIONAL')),
    CONSTRAINT fk_cliente_registrado_por   FOREIGN KEY (registrado_por_id) REFERENCES usuario (id),
    CONSTRAINT fk_cliente_editado_por      FOREIGN KEY (editado_por_id) REFERENCES usuario (id)
);

-- PostgreSQL no crea índices para las FK por su cuenta; este acelera "clientes registrados por X"
CREATE INDEX idx_cliente_registrado_por ON cliente (registrado_por_id);