spring:
  application:
    name: crm-backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    
jwt:
  secreto: ${JWT_SECRET}
  expiracion-segundos: 28800